export const plataformsArray = [
  "Atari ST",
  "Linux",
  "Game Boy Advance",
  "GameCube",
  "macOS",
  "Nintendo Switch",
  "Nintendo 3DS",
  "PC",
  "PlayStation 1",
  "PlayStation 2",
  "PlayStation 3",
  "PlayStation 4",
  "PlayStation 5",
  "PS Vita",
  "Xbox 360",
  "Xbox One",
  "Xbox Series S/X",
  "SEGA",
  "Wii  ",
  "Wii U",
];
